// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ethnicity options for job submission.
 *
 * # Variants
 * * `AfricanAmerican` - African American/Black
 * * `NativeAmerican` - Native American/American Indian
 * * `Asian` - Asian
 * * `Hispanic` - Hispanic/Latino
 * * `Caucasian` - Caucasian/White
 * * `PacificIslander` - Pacific Islander
 */
export type Ethnicity =
	| 'africanAmerican'
	| 'nativeAmerican'
	| 'asian'
	| 'hispanic'
	| 'caucasian'
	| 'pacificIslander';
