// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ethnicity } from './Ethnicity';
import type { JobStatus } from './JobStatus';
import type { Sex } from './Sex';

/**
 * The job struct, which contains the job
 *
 * # Fields
 * * `age` - The age of the patient
 * * `ethnicity` - The ethnicity of the patient
 * * `sex` - The assigned sex of the patient
 * * `height` - The height of the patient
 * * `status` - The status of the job
 * * `timestamp` - The timestamp of the job (Unix timestamp in seconds)
 * * `weight` - The weight of the patient
 * * `email` - The email of the person who submitted the job
 * * `requires_approval` - Whether the user requested manual approval for this job
 * * `approved` - Whether this job has been approved for processing
 */
export type Job = {
	age: number;
	ethnicity: Ethnicity;
	sex: Sex;
	height: string;
	status: JobStatus;
	timestamp: number;
	weight: number;
	email: string;
	/**
	 * Whether this job requires manual approval before processing
	 */
	requires_approval: boolean;
	/**
	 * Whether this job has been approved for processing
	 */
	approved: boolean;
	/**
	 * Per-stage logs collected during processing.
	 * Keys are "stage_1" through "stage_7", values are the log text.
	 */
	stage_logs: Record<string, string>;
};
