// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobStatus } from "./JobStatus";

/**
 * The job struct, which contains the job
 * 
 * # Fields
 * * `age` - The age of the patient
 * * `ethnicity` - The ethnicity of the patient
 * * `sex` - The assigned sex of the patient
 * * `height` - The height of the patient
 * * `status` - The status of the job
 * * `timestamp` - The timestamp of the job (Unix timestamp in seconds)
 * * `weight` - The weight of the patient
 * * `email` - The email of the person who submitted the job
 */
export type Job = { age: number, ethnicity: string, sex: string, height: string, status: JobStatus, timestamp: number, weight: number, email: string, };
