// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The job status code enum, which contains the status codes for the job.
 * 
 * # Variants
 * * `Submitting` - The job is downloading on AWS
 * * `SubmissionErr` - The job download has errored on AWS
 * * `Queue` - The job is in the queue on AWS to be sent to Metis
 * * `Processing` - The job is processing on Metis
 * * `InferenceErr` - The job has errored during inference on Metis
 * * `Complete` - The job has completed successfully
 */
export type JobStatusCode = "Submitting" | "SubmissionErr" | "Queue" | "Processing" | "InferenceErr" | "Complete";
