// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobStatusCode } from "./JobStatusCode";

/**
 * The job status struct, which contains the status of the job.
 * 
 * # Fields
 * * `code` - The status code of the job
 * * `value` - The human-readable value of the status
 */
export type JobStatus = { code: JobStatusCode, value: string, };
