// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User role options - who is completing the submission form.
 *
 * # Variants
 * * `Parent` - Parent of the patient
 * * `Doctor` - Medical professional
 * * `SchoolOfficial` - School nurse or administrator
 * * `Sibling` - Sibling of the patient
 * * `Grandparent` - Grandparent of the patient
 * * `Self_` - Patient themselves
 */
export type UserRole = 'parent' | 'doctor' | 'schoolOfficial' | 'sibling' | 'grandparent' | 'self';
