// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Job } from './Job';

/**
 * The user struct, which contains a user ID and a list of jobs.
 *
 * # Fields
 * * `uid` - The user ID
 * * `jobs` - The list of jobs
 * * `administrator` - Whether the user has administrator privileges
 */
export type User = { uid: string; jobs: Array<Job>; administrator: boolean };
